### ISSUE TITLE
Enable PubSub in the Browser

### ISSUE THREAD

**Issue by daviddias** [ipfs/js-ipfs-http-client#518]
> Following: https://github.com/ipfs/js-ipfs-api/pull/493#issuecomment-268603853

PubSub will be unavailable as a browser API until https://github.com/ipfs/http-api-spec/issues/116 happens.

**Comment by diasdavid** [comment]
Update on this thread:

We currently have PubSub disabled on the browser as a way to prevent misunderstanding how the cancellation of the API works. Unfortunately, due to what is noted in -- https://github.com/ipfs/js-ipfs-api/pull/493#issuecomment-268603853 -- we simply can't cancel requests as go-ipfs expects in the browser. However, it seems to me that removing support for it entirely is not the optimal solution, as for a lot of use cases, only a few amount of PubSub channels will be open from a client, keeping the maintenance of those at bare minimum.

Proposal: enable PubSub and be explicit that cancels aren't actually being canceled, just silenced.

**Comment by mitar** [comment]
Just curious, why cancellation does not work?

**Comment by mitar** [comment]
I think we should enable PubSub on client and document cancelation issue.

**Comment by Morantron** [comment]
I've found and ultra-hacky workaround to cancel fetch requests without XHR here ( https://github.com/Morantron/poor-mans-cancelable-fetch ).

The whole idea is to make requests in a seperate WebWorker, and sending a signal to the worker to terminate itself, which also aborts the request :trollface:

Eventually fetch requests will be able to be aborted ( https://github.com/whatwg/fetch/issues/447 ), but the final API hasn't been decided yet.

I know it's super hackish, but if it works :tm: , it can serve as workaround until fetch requests are abortable.

**Comment by mitar** [comment]
Great hack! I like it!

**Comment by diasdavid** [comment]
Oh wow! @Morantron wanna submit a PR with that feature? Can you make sure to add a check to see if the browser has WebWorker support?

**Comment by Morantron** [comment]
@diasdavid Sure! I'm gonna see if I can turn the hack into some kind of FetchController polyfill, and then make the needed changes in js-ipfs-api.

Looks like [IE11 does not support fetch](http://caniuse.com/#feat=fetch), so I guess PubSub won't work given that XHR does not play well with http streams.

**Comment by jedd-ahyoung** [comment]
Hey, all, hate to ask a potentially obvious (and stupid) question.....but why not just use standard XHR which is cancellable? Believe me, I support the fetch standard and I love what it provides, but if we aren't using a service worker to intercept requests or anything like that, the main difference comes down to error handling.

XHR requests are cancellable and would solve the issue until the fetch standard includes true cancellable requests. The other alternative to this to cancel requests on the client side would be to run a service worker, and have the service worker respond to the request with a 400 Cancelled or something like that when a cancellation is requested. (Basically, you're manually sending a response to an initiated HTTP request to terminate it early.)

**Comment by diasdavid** [comment]
@jedd-ahyoung xhr is not streamable, pubsub/subscribe is a stream. We need to use something like fetch or make this endpoint available Websockets.

**Comment by mitar** [comment]
Yes, why not websockets? Or dataframes from WebRTC?

**Comment by diasdavid** [comment]
This is not a decision at the level of this client library, it is rather at the http-api spec level. Moving to a complete RPC API where WebSockets is used as a transport has been proposed: https://github.com/ipfs/http-api-spec/issues/116

**Comment by diasdavid** [comment]
### Update

The decision on this one is to either do:

a) Enable PubSub and fake subscriptions - https://github.com/ipfs/js-ipfs-api/issues/518#issuecomment-298729383
b) Use WebWorkers to cancel subscriptions - https://github.com/ipfs/js-ipfs-api/issues/518#issuecomment-302868838

Either is fine as a first iteration.

**Comment by nunofmn** [comment]
It's important to notice that Edge 16 and Firefox 57 now can cancel fetch requests by using [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController/AbortController) and [AbortSignal](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal). But Chrome still doesn't support this API...

**Comment by VictorBjelkholm** [comment]
Seems Chrome has done some work on it, last patch from February 5th this year https://bugs.chromium.org/p/chromium/issues/detail?id=750599

WebKit, no status yet: https://bugs.webkit.org/show_bug.cgi?id=174980

**Comment by VictorBjelkholm** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/API/AbortController#Browser_compatibility most browsers now work with AbortController (except IE, shocker)

![image](https://user-images.githubusercontent.com/459764/43733127-e6049a02-99b3-11e8-9a47-b45761cd99f6.png)

**Comment by shunkino** [comment]
Hi, I'm new to the ipfs community and impressed by the all works done so far.
I find the PubSub functionality very interesting and which it be work in browsers too.

Here are my findings. Maybe I'm totally off the track, please let me know if anything is wrong.
In my understanding, the problem here is that we can't cancel requests in browser by the code bellow.
https://github.com/ipfs/js-ipfs-api/blob/master/src/pubsub.js#L94
But, as [@nunofmn suggest](https://github.com/ipfs/js-ipfs-api/issues/518#issuecomment-346905572) if we can use AbortController, we can cancel the fetch.

Since [js-ipfs-api uses `stream-http` as `http`](https://github.com/ipfs/js-ipfs-api/blob/e61155ae8edaee902cb3a1dcd8ba3d3afb093d1c/package.json#L11), aborting function should be implemented using it's API. When looking at the code of the `stream-http` library, abort() to the client request is [implemented](https://github.com/jhiesey/stream-http/blame/master/lib/request.js#L286) at [v2.7.2](https://github.com/jhiesey/stream-http/compare/v2.7.2...master). Thus, required version of `stream-http` by `package.json`, v2.8.3, should already have this API. Looks like just calling abort() to the request object is enough(=same as node). 

So, isn't this mean we can use same codebase as node to get this "cancellable fetch" working in the browser? I'd love to test my idea but I'm not sure how to do so yet, so just posting comment. Hope this helps.

**Comment by alanshaw** [comment]
This sounds reasonable to me @shunkino - I'd ❤️ to see a proposal PR 😄

**Comment by shunkino** [comment]
I've made a change to the /src/pubsub.js according to my findings above. But something is still wrong, and I was debugging that these few days. Unfortunately, I'm stack now and need help... 

I modified the pubsub.js as below. It's basically adding condition to detect whether the browser have the AbortController functionality. 
https://gist.github.com/shunkino/baf26def13aca1ae6949d3ff1e0f939b

Modified version seems to work properly inside browser, but failing the test in `interface-ipfs-core`.
```
    .pubsub.publish
      ✓ should error on string messags
      ✓ should publish message from buffer (42ms)
      ✓ should publish 10 times within time limit (251ms)
    .pubsub.subscribe
      single node
        1) should subscribe to one topic
        2) should subscribe to one topic (promised)
        3) should subscribe to one topic with options
        4) should subscribe to one topic with options (promised)
        5) should subscribe to topic multiple times with different handlers
        6) should allow discover option to be passed
      multiple connected nodes
        ✓ should receive messages from a different node (77ms)
        7) "after each" hook for "should receive messages from a different node"
    .pubsub.unsubscribe
      8) should subscribe and unsubscribe 10 times
    .pubsub.peers
      ✓ should not error when not subscribed to a topic (51ms)
      9) should not return extra peers
      10) should return peers for a topic - one peer
      11) should return peers for a topic - multiple peers
    .pubsub.ls
      ✓ should return an empty list when no topics are subscribed (14ms)
      12) should return a list with 1 subscribed topic
      13) should return a list with 3 subscribed topics
```

To identify why the test is failing, I created the small app based on the example.
(I deployed the test app to `/ipfs/Qme1GWMpHuErWGcGXbF7NsDBNKB5yMsT8sSeRP3s8wopQ1/` 😜 You can debug it inside browser. Click `testFunction` button to test.)

Looks like callback [here](https://gist.github.com/shunkino/3c9ff24feb2816326c335287c6f71c27#file-index-js-L88) is not called. 

Furthermore, Inside the `unsubscribe()`, [callback given to the `eos()`](https://github.com/ipfs/js-ipfs-api/blob/master/src/pubsub.js#L101) was not called. I don't know anything about `end-of-stream` and `once` library it depends. Also it was difficult to dig deeper so I'm stack here now.

Suspicious factors:
- Event emitting from `stream-http`, `readable-stream` 
- Function wrapper in `eos()`, `once` library

Same function worked perfectly in node.js. Any comment and advice are welcome, thank you.

**Comment by shunkino** [comment]
I just noticed on my Firefox (Quantum 61.0.2 64bit on macOS) the code worked... 
Maybe there's some browser dependent code causing [above mentioned problem](https://github.com/ipfs/js-ipfs-api/issues/518#issuecomment-419324459).

**Comment by klueq** [comment]
Is there a way to enable `pubsub` locally?

**Comment by whyrusleeping** [comment]
any updates here?

**Comment by mccoysc** [comment]
@whyrusleeping

**Comment by daviddias** [comment]
@shunkino did you happen to make a PR with your progress?
